/* !---- DO NOT EDIT: This file autogenerated by com\sun\gluegen\JavaEmitter.java on Tue May 27 02:37:55 PDT 2008 ----! */

#include <jni.h>
#include <cstdlib>

#include <cassert>

#include "jau_sys_dl_WindowsDynamicLinkerImpl.h"

#if defined(_WIN32)

 #include <windows.h>
 /* This typedef is apparently needed for compilers before VC8,
    and for the embedded ARM compilers we're using */
 #if !defined(__MINGW64__) && ( (_MSC_VER < 1400) || defined(UNDER_CE) )
     typedef int intptr_t;
 #endif
 /* GetProcAddress doesn't exist in A/W variants under desktop Windows */
 #ifndef UNDER_CE
 #define GetProcAddressA GetProcAddress
 #endif

/*   Java->C glue code:
 *   Java package: jogamp.common.os.WindowsDynamicLinkerImpl
 *    Java method: int FreeLibrary(long hLibModule)
 *     C function: BOOL FreeLibrary(HANDLE hLibModule);
 */
JNIEXPORT jint JNICALL 
Java_jau_sys_dl_WindowsDynamicLinkerImpl_FreeLibrary(JNIEnv *env, jclass _unused, jlong hLibModule) {
  (void)env;
  (void)_unused;

  BOOL _res;
  _res = FreeLibrary((HANDLE) (intptr_t) hLibModule);
  return _res;
}


/*   Java->C glue code:
 *   Java package: jogamp.common.os.WindowsDynamicLinkerImpl
 *    Java method: int GetLastError()
 *     C function: DWORD GetLastError(void);
 */
JNIEXPORT jint JNICALL 
Java_jau_sys_dl_WindowsDynamicLinkerImpl_GetLastError(JNIEnv *env, jclass _unused) {
  (void)env;
  (void)_unused;

  DWORD _res;
  _res = GetLastError();
  return _res;
}


/*   Java->C glue code:
 *   Java package: jogamp.common.os.WindowsDynamicLinkerImpl
 *    Java method: long GetProcAddressA(long hModule, java.lang.String lpProcName)
 *     C function: PROC GetProcAddressA(HANDLE hModule, LPCSTR lpProcName);
 */
JNIEXPORT jlong JNICALL 
Java_jau_sys_dl_WindowsDynamicLinkerImpl_GetProcAddressA(JNIEnv *env, jclass _unused, jlong hModule, jstring lpProcName) {
  (void)_unused;

  const char* _strchars_lpProcName = nullptr;
  PROC _res;
  if (lpProcName != nullptr) {
    _strchars_lpProcName = env->GetStringUTFChars(lpProcName, (jboolean*)nullptr);
    if (_strchars_lpProcName == nullptr) {
      env->ThrowNew(env->FindClass("java/lang/OutOfMemoryError"),
                       "Failed to get UTF-8 chars for argument \"lpProcName\" in native dispatcher for \"GetProcAddressA\"");
      return 0;
    }
  }
  _res = GetProcAddressA((HANDLE) (intptr_t) hModule, (LPCSTR) _strchars_lpProcName);
  if (lpProcName != nullptr) {
    env->ReleaseStringUTFChars(lpProcName, _strchars_lpProcName);
  }
  return (jlong) (intptr_t) _res;
}


/*   Java->C glue code:
 *   Java package: jogamp.common.os.WindowsDynamicLinkerImpl
 *    Java method: long LoadLibraryW(java.lang.String lpLibFileName)
 *     C function: HANDLE LoadLibraryW(LPCWSTR lpLibFileName);
 */
JNIEXPORT jlong JNICALL 
Java_jau_sys_dl_WindowsDynamicLinkerImpl_LoadLibraryW(JNIEnv *env, jclass _unused, jstring lpLibFileName) {
  (void)_unused;

  jchar* _strchars_lpLibFileName = nullptr;
  HANDLE _res;
  if (lpLibFileName != nullptr) {
    _strchars_lpLibFileName = (jchar *) calloc(env->GetStringLength(lpLibFileName) + 1, sizeof(jchar));
    if (_strchars_lpLibFileName == nullptr) {
      env->ThrowNew(env->FindClass("java/lang/OutOfMemoryError"),
                       "Could not allocate temporary buffer for copying string argument \"lpLibFileName\" in native dispatcher for \"LoadLibraryW\"");
      return 0;
    }
    env->GetStringRegion(lpLibFileName, 0, env->GetStringLength(lpLibFileName), _strchars_lpLibFileName);
  }
  _res = LoadLibraryW((LPCWSTR) _strchars_lpLibFileName);
  if (lpLibFileName != nullptr) {
    free((void*) _strchars_lpLibFileName);
  }
  return (jlong) (intptr_t) _res;
}

#endif /* _WIN32 */
